# --- 1. Aşama: Build (Derleme) ---
# Vite+React projesini build etmek için Node kullan
FROM node:20-slim AS builder
WORKDIR /app


COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci


COPY frontend/ ./

# Projeyi build et (frontend/dist klasörünü oluşturur)
RUN npm run build

# --- 2. Aşama: Production (Sunucu) ---

FROM nginx:alpine

# Nginx ayarı:
# 1. React (SPA) için 'try_files' (404'leri index.html'e yönlendir)
# 2. '/api' isteklerini 'api' servisine (http://api:5001) proxy'le
RUN echo "server { \
      listen 80; \
      location / { \
        root   /usr/share/nginx/html; \
        index  index.html index.htm; \
        try_files \$uri \$uri/ /index.html; \
      } \
      location /api { \
        proxy_pass http://api:5001; \
        proxy_set_header Host \$host; \
        proxy_set_header X-Real-IP \$remote_addr; \
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; \
      } \
    }" > /etc/nginx/conf.d/default.conf

# Build aşamasından (builder) build edilmiş dosyaları (/app/dist) 
# Nginx'in sunucu klasörüne kopyala
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]